pool:
  vmImage: "Ubuntu 16.04"

trigger:
  # Do not build branches
  branches:
    include:
      - "fix-build-namespace"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master
  - release/*

steps:
  - bash: |
      git rev-parse HEAD
    displayName: "Configure AWS Namespace"
