pool:
  vmImage: "Ubuntu 16.04"

trigger:
  # Do not build branches
  branches:
    include:
      - "fix-build-namespace"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master
  - release/*

steps:
  - bash: |
      git status
      git remote -v
      git branch -a
      pwd
      git log -n 3
      git rev-parse HEAD
      git show -s --pretty=%d HEAD
    displayName: "Configure AWS Namespace"
